version: "3"

services:
  web:
    tty: true
    build: 
      context: .
      dockerfile: ./server/dockerfile
    container_name: ctfYumRPM_repo
    ports: 
     - 8080:80
  
  client:
    tty: true
    build:
      context: .
      dockerfile: ./client/dockerfile
    container_name: ctfYumRPM_client